// Navigation bar
export const navItems = [
  { label: "Home", href: "#" },
  { label: "Rooms", href: "/not-found" },
  { label: "Amenities", href: "/not-found" },
  { label: "Events", href: "/not-found" },
];

export const LOCAL_IMAGES = [
  "/images/pic1.webp",
  "/images/pic2.webp",
  "/images/pic3.webp",
  "/images/pic4.webp",
  "/images/pic5.webp",
  "/images/pic6.webp",
  "/images/pic7.webp",
  "/images/pic8.webp",
  "/images/pic9.webp",
  "/images/pic10.webp",
  "/images/pic11.webp",
  "/images/pic12.webp",
  "/images/pic13.webp",
  "/images/pic14.webp",
  "/images/pic15.webp",
  "/images/pic16.webp",
  "/images/pic17.webp",
  "/images/pic18.webp",
  "/images/pic19.webp",
  "/images/pic20.webp",
  "/images/pic21.webp",
  "/images/pic22.webp",
  "/images/pic23.webp",
  "/images/pic24.webp",
  "/images/pic25.webp",
  "/images/pic26.webp",
  "/images/pic27.webp",
  "/images/pic28.webp",
  "/images/pic29.webp",
];
